### ISSUE TITLE
Messkampagnen erstellen: mit Überblicksseite über Räume und Personen

### ISSUE THREAD

**Issue by silvioheinze** [luftdaten-at/datahub#23]
und Verwalten (was und wie genau?)

**Comment by n11ik** [comment]
## Konzeptionelle Fragen

1. Werden die Organisationen von uns auf Anfrage erstellt oder können User auch Organisationen erstellen?
1.1 Das selbe für Kampagnen
3. Wer kann Geräte zu Kampagnen zuordnen?
4. Gibt es den Spezialfall, dass ein User mehreren Organisationen angehört?
5. Können bei einer Kampagne nur User dabei sein, die auch der Organisation der Kampagne zugeordnet sind?

**Comment by silvioheinze** [comment]
> Werden die Organisationen von uns auf Anfrage erstellt oder können User auch Organisationen erstellen?
User sollten es auch erstellen sollen. Vielleicht in ihrem Profil, wo sie sich einer Organisation zuordnen können. Oder es gibt einen Organisationsmanager pro Organisation, welcher dies zuordnen kann.

> 1.1 Das selbe für Kampagnen
User sollten neue Kampagnen erstellen können und sind dann automatisch Kampagnenmanager.

> Wer kann Geräte zu Kampagnen zuordnen?
Im Datahub erstmal nur wir. Eventuell gibt es spezielle Rechte für Accounts, die der Organisation „Luftdaten“ zugeordnet wurden?

> Gibt es den Spezialfall, dass ein User mehreren Organisationen angehört?
Erstmal: nein.

> Können bei einer Kampagne nur User dabei sein, die auch der Organisation der Kampagne zugeordnet sind?
Ja, weil ich würde die Userverwaltung an die Organisation hängen. Betriebsräte können so ihre Mitglieder eintragen und verschiedene Messkamapgnen starten, ohne diese wieder neu einzutragen.

**Comment by n11ik** [comment]
**TODO**
- campaign form attribute: public, organization und users entfernen
- campaign detail view: rooms und users hinzufügen
- profile page

**Comment by n11ik** [comment]
Guide for styling FilterdSelectMultiple: https://gist.github.com/s-boardman/811ad38613f3eb9cfea214bcce10f918
