### ISSUE TITLE
Datenbankmodell update aus API

### ISSUE THREAD

**Issue by silvioheinze** [luftdaten-at/datahub#51]

**Comment by n11ik** [comment]
@silvioheinze ich habe die models.py mal auf das aktuelle model geändert.
Wenn ich haber dann die migration durchführen will: `docker compose exec app python manage.py makemigrations`,
kommt diese warnung:
```
It is impossible to add a non-nullable field 'id' to sensor without specifying a default. This is because the database needs something to populate existing rows.
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit and manually define a default value in models.py.
Select an option: 
```
Weil ich keine änderungen in der Sensor Klasse gemacht habe, habe ich die migrations ohnen meinen änderungen getestet und es kommt die selbe warnung.

Wie hast du bis jetzt die migrationen gemacht?
