### ISSUE TITLE
Oranization management

### ISSUE THREAD

**Issue by n11ik** [luftdaten-at/datahub#71]
- Create Organizations
- Add users

**Comment by n11ik** [comment]
TODO
Test if invitation email gets sent on staging
email: add link to registration site

**Comment by n11ik** [comment]
@silvioheinze ich habe jetzt die funktion implementiert, dass man user einladen kann und eine E-Mail gesendet wird fals noch kein user mit der E-Mail vorhanden ist.

Lokal bekomme ich folgenden fehler wenn ich eine E-Mail vom server schicken will:

```django
<h1>ConnectionRefusedError
       at /campaigns/organizations/2/invite-user</h1>
  <pre class="exception_value">[Errno 111] Connection refused</pre>
  
Request Method: | POST
-- | --
http://localhost/campaigns/organizations/2/invite-user
5.1.2
ConnectionRefusedError
[Errno 111] Connection refused
/usr/local/lib/python3.12/socket.py, line 850, in create_connection
campaign.views.invite_user_to_organization
/usr/local/bin/python
3.12.8
['/usr/src/app',  '/usr/local/lib/python312.zip',  '/usr/local/lib/python3.12',  '/usr/local/lib/python3.12/lib-dynload',  '/usr/local/lib/python3.12/site-packages']
Wed, 18 Dec 2024 13:21:29 +0100
```

Weißt du ob das Problem nur Lokal auftritt oder ob man da nochwas einstellen muss?
Das .env file sollte bei mir die selben Einstellungen haben wie auf dem production system.

Kann es sein, dass wir da noch unseren Mail-Server eintragen müssen?

**.env**
```.env
EMAIL_HOST=mail.your-server.de
```

**Comment by silvioheinze** [comment]
mail.your-server.de ist der E-Mail-Server von Hetzner. Das sollte so passen.
